# Numpy array

In [69]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mat = np.array(my_mat)

In [9]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# with step for even numbers
np.arange(0, 10, 2) 

array([0, 2, 4, 6, 8])

In [ ]:
# Specific types of arrays

In [15]:
# array of all zeros
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# array of pure ones
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# array for evenly spaced values
# np.arange(0, 10, step=2)
np.linspace(0, 10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
# create an identify matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random numbers

In [23]:
# vector
np.random.rand(5)

array([0.40220233, 0.98167701, 0.90068448, 0.10676175, 0.05786153])

In [24]:
# matrix
np.random.rand(3, 5)

array([[0.9588406 , 0.20741036, 0.23189305, 0.35447419, 0.6781161 ],
       [0.28157583, 0.76661027, 0.96411071, 0.25650393, 0.67781338],
       [0.07957783, 0.91717471, 0.07822041, 0.18940327, 0.98870748]])

In [25]:
np.random.rand(3, 5, 4)

array([[[0.16367044, 0.63173139, 0.21423819, 0.24436586],
        [0.20345253, 0.29053851, 0.29142248, 0.21147809],
        [0.87397515, 0.70887436, 0.83149746, 0.96717654],
        [0.33979281, 0.56351743, 0.90411611, 0.18035795],
        [0.82366039, 0.44346434, 0.98387364, 0.15220413]],

       [[0.9208004 , 0.40996951, 0.59154015, 0.98467589],
        [0.18672574, 0.19814612, 0.03088657, 0.33328801],
        [0.26072572, 0.48556731, 0.00651578, 0.55006438],
        [0.39452043, 0.53518714, 0.06736002, 0.63041914],
        [0.23054337, 0.1801138 , 0.13879063, 0.0205678 ]],

       [[0.87115407, 0.9049001 , 0.84889639, 0.47561147],
        [0.21044605, 0.52384308, 0.41775315, 0.31135046],
        [0.73945152, 0.969889  , 0.96338565, 0.36741069],
        [0.46740815, 0.80087742, 0.49682113, 0.23263972],
        [0.44367898, 0.86941779, 0.49545449, 0.43808528]]])

In [26]:
# samples from the standard normal distribution or a Gaussian distribution
np.random.randn(3)

array([ 0.08255997, -1.54777308,  1.18983959])

In [27]:
np.random.randn(3, 3)

array([[ 1.28102444, -1.36520753, -1.39898957],
       [ 0.68329166,  1.02709248,  1.07603981],
       [-0.98265184,  0.43639884, -0.56869301]])

In [30]:
# random integers
np.random.randint(2, high=5, size=3)

array([4, 3, 3], dtype=int32)

## useful attributes and methods

In [ ]:
# shape of an array

In [44]:
arr = np.arange(25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
randarr = np.random.randint(0, 100, 10)

In [38]:
randarr

array([79, 43, 13, 36, 12, 62, 53, 97, 94, 62], dtype=int32)

In [56]:
arr.shape

(25,)

In [57]:
randarr.shape

(10,)

In [46]:
# reshaping
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr = arr.reshape(5, 5)

In [59]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.shape

(5, 5)

In [ ]:
# what is the result of this line of code
arr.reshape(5, 6)

In [47]:
# finding max and min values

In [48]:
randarr

array([79, 43, 13, 36, 12, 62, 53, 97, 94, 62], dtype=int32)

In [49]:
randarr.max()

np.int32(97)

In [50]:
randarr.min()

np.int32(12)

In [ ]:
# location of max and min values

In [51]:
randarr.argmax()

np.int64(7)

In [52]:
randarr.argmin()

np.int64(4)

In [55]:
print(f"The largest number {randarr.max()} is located at index {randarr.argmax()}")

The largest number 97 is located at index 7


In [54]:
print(f"The smallest number {randarr.min()} is located at index {randarr.argmin()}")

The smallest number 12 is located at index 4


In [62]:
# data types of arrays

In [63]:
arr.dtype

dtype('int64')

In [64]:
randarr.dtype

dtype('int32')

In [65]:
# change the data type
arr.astype("float64")

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [68]:
randarr.astype("int64")

array([79, 43, 13, 36, 12, 62, 53, 97, 94, 62])

# Numpy indexing and selection

In [70]:
arr = np.arange(0, 11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# pick out one element
arr[4]

np.int64(4)

In [73]:
# values in a range, ":" clicing notation
arr[1:5]

array([1, 2, 3, 4])

In [74]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [75]:
# remove the start point and end point
arr[:5]

array([0, 1, 2, 3, 4])

In [76]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
# Numpy arrays differ from normal python list because of the ability of broadcast

In [78]:
# broadcast a value 100 to the first 5 elements in the array
arr[0:5] = 100

In [79]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [80]:
# reset the array
arr = np.arange(0, 11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
# important attribute of slicing the array
slice_of_arr = arr[0:5]

In [88]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [89]:
# broadcast on this slice of array
slice_of_arr[:] = 99

In [86]:
slice_of_arr

99

In [91]:
# the change to the slice also happens to the original array
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [92]:
# a copy of the array

In [93]:
arr_copy = arr.copy()

In [94]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [95]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [96]:
arr_copy[:] = 100

In [97]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [98]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## indexing on 2-d arrays

In [99]:
arr_2d = np.array([[1, 2, 3],[11, 22, 33], [111, 222, 333]])

In [100]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [101]:
# two general format to slice 2-d arrays
# double bracket [][]
# single bracket [,], recommended

In [102]:
# double bracket [][]
arr_2d[0][0]

np.int64(1)

In [103]:
arr_2d[0]

array([1, 2, 3])

In [104]:
arr_2d[0][0]

np.int64(1)

In [105]:
arr_2d[1][1]

np.int64(22)

In [106]:
arr_2d[2][1]

np.int64(222)

In [108]:
arr_2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [107]:
# single bracket [,], recommended
arr_2d[0, 0]

np.int64(1)

In [109]:
# 33
arr_2d[1, 2]

np.int64(33)

In [112]:
# specific chunks of an array, sub-matrix or sub-array
# array([[  2,   3],
#        [ 22,  33]])
arr_2d[:2,1:]

array([[ 2,  3],
       [22, 33]])

In [113]:
# array([[ 11,  22],
#        [111, 222]])
arr_2d[1:,:2]

array([[ 11,  22],
       [111, 222]])

In [114]:
arr_2d[1:]

array([[ 11,  22,  33],
       [111, 222, 333]])

In [116]:
# no double bracket format
arr_2d[1:][:2]

array([[ 11,  22,  33],
       [111, 222, 333]])

In [117]:
arr_2d[1:,:2]

array([[ 11,  22],
       [111, 222]])

# conditional selection

In [121]:
arr = np.arange(1, 11)

In [122]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
# get a full boolean array out of this array
# compare it with a single digit
arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [125]:
bool_arr = arr > 7

In [126]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [127]:
bool_arr.dtype

dtype('bool')

In [128]:
# boolean array can be used to do conditional selection.

In [130]:
arr[bool_arr]

array([ 8,  9, 10])

In [131]:
arr[arr > 7]

array([ 8,  9, 10])

In [132]:
# all elements less than 3
arr[arr < 3]

array([1, 2])

# Numpy operations
## - Array with array
## - Array with scalars
## - Universal Array Functions (https://numpy.org/doc/stable/user/basics.ufuncs.html)

In [135]:
arr = np.arange(0, 11)

In [136]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
# addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [138]:
# subtraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
# multiplication (element-wise multiplication)
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [140]:
# with scalars (element-wise)
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [141]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [142]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [143]:
# division, pure python vs numpy
1 / 0

ZeroDivisionError: division by zero

In [144]:
arr / arr

C:\Users\wagu0\AppData\Local\Temp\ipykernel_5480\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [145]:
1 / arr

C:\Users\wagu0\AppData\Local\Temp\ipykernel_5480\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [146]:
# power
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## universal functions

In [148]:
# square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [151]:
# exponential of all elements
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [154]:
arr.max()

np.int64(10)

In [152]:
np.max(arr)

np.int64(10)

In [155]:
arr.min()

np.int64(0)

In [153]:
np.min(arr)

np.int64(0)

In [156]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [157]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [158]:
# logrithmic
# log of zero is technically negtive infinity
np.log(arr)

C:\Users\wagu0\AppData\Local\Temp\ipykernel_5480\2835728015.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Exercises

In [ ]:
# do again all operations mentioned above and maybe more and with larger arrays

In [133]:
arr_2d = np.arange(50).reshape(5, 10)

In [134]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [119]:
# Print odd numbers before 100

In [120]:
# grab arbitrary sub-array from a given array (2-d), make a bigger array and grab some larger sub-arrays